version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/lonnblad/circle-ci-test
    docker:
      - image: circleci/golang:1.14.4
    steps:
      - checkout
      - run:
          name: "create dir"
          command: mkdir /tmp/workspace
      - run:
          name: "build"
          command: |
            go build -o /tmp/workspace/hello-world main.go
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /tmp/workspace
          # Must be relative path from root
          paths:
            - hello-world
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            # VERSION=$(my-binary --version)
            ghr \
             -t ${GITHUB_TOKEN} \
             -u ${CIRCLE_PROJECT_USERNAME} \
             -r ${CIRCLE_PROJECT_REPONAME} \
             -c ${CIRCLE_SHA1} \
            #  -delete ${VERSION} \
             -delete v1.0.0 \
             ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v\d+\.\d+\.\d+$/
