version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/lonnblad/circle-ci-test
    docker:
      - image: circleci/golang:1.14.4
    steps:
      - checkout
      - run:
          name: "build"
          command: |
            go build -o hello-world main.go
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - hello-world
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr \
             -t ${GITHUB_TOKEN} \
             -u ${CIRCLE_PROJECT_USERNAME} \
             -r ${CIRCLE_PROJECT_REPONAME} \
             -c ${CIRCLE_SHA1} \
             -delete ${VERSION} \
             ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
